name: Generate changelog
# Trigger the workflow on pull request activity
on:
  push:
    branches:
      - master
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        git-message: 'chore(release): {version}'
        release-count: '0'
